# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Tim Cane

name: "Release dev container features"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Commit generated docs"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated docs update [skip ci]"
          branch: main
          file_pattern: README.md src/**/README.md
